/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingInquiry {
  'id' : bigint,
  'checkIn' : string,
  'name' : string,
  'email' : string,
  'timestamp' : Time,
  'checkOut' : string,
  'guests' : bigint,
  'roomType' : RoomType,
}
export type RoomType = { 'familySuite' : null } |
  { 'deluxeRoom' : null } |
  { 'executiveSuite' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllBookings' : ActorMethod<[], Array<BookingInquiry>>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, RoomType, bigint],
    BookingInquiry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];