/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const RoomType = IDL.Variant({
  'familySuite' : IDL.Null,
  'deluxeRoom' : IDL.Null,
  'executiveSuite' : IDL.Null,
});
export const BookingInquiry = IDL.Record({
  'id' : IDL.Nat,
  'checkIn' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'checkOut' : IDL.Text,
  'guests' : IDL.Nat,
  'roomType' : RoomType,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, RoomType, IDL.Nat],
      [BookingInquiry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const RoomType = IDL.Variant({
    'familySuite' : IDL.Null,
    'deluxeRoom' : IDL.Null,
    'executiveSuite' : IDL.Null,
  });
  const BookingInquiry = IDL.Record({
    'id' : IDL.Nat,
    'checkIn' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'checkOut' : IDL.Text,
    'guests' : IDL.Nat,
    'roomType' : RoomType,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, RoomType, IDL.Nat],
        [BookingInquiry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };